nis_file_location: "https://docs.google.com/spreadsheets/d/12AlJ0tdu2b-cfalNzLqFYfiC-hdDlIv1M1pTE3AfSWY/edit#gid=1986791705"
correspondence_files_path: ""
simulation_type: sentinel
simulation_files_path: ""
lci_data_locations:
  - ""
output_directory: ""
